// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRender(arg1) {
  return window['go']['main']['App']['CancelRender'](arg1);
}

export function DefaultExportName(arg1) {
  return window['go']['main']['App']['DefaultExportName'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function ExportRender(arg1, arg2) {
  return window['go']['main']['App']['ExportRender'](arg1, arg2);
}

export function InspectInput(arg1) {
  return window['go']['main']['App']['InspectInput'](arg1);
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function PauseRender(arg1) {
  return window['go']['main']['App']['PauseRender'](arg1);
}

export function ResumeRender(arg1) {
  return window['go']['main']['App']['ResumeRender'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SavePreset(arg1) {
  return window['go']['main']['App']['SavePreset'](arg1);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectOutputDir(arg1) {
  return window['go']['main']['App']['SelectOutputDir'](arg1);
}

export function SetDrawFocus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetDrawFocus'](arg1, arg2, arg3, arg4);
}

export function StartRender(arg1) {
  return window['go']['main']['App']['StartRender'](arg1);
}
