// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {main} from '../models';

export function CancelRender(arg1:string):Promise<void>;

export function DefaultExportName(arg1:string):Promise<string>;

export function DeletePreset(arg1:string):Promise<void>;

export function ExportRender(arg1:string,arg2:session.ExportOptions):Promise<Array<string>>;

export function InspectInput(arg1:string):Promise<main.InputInfo>;

export function ListPresets():Promise<Array<session.Preset>>;

export function PauseRender(arg1:string):Promise<void>;

export function ResumeRender(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SavePreset(arg1:session.Preset):Promise<void>;

export function SelectInputFile():Promise<string>;

export function SelectOutputDir(arg1:string):Promise<string>;

export function SetDrawFocus(arg1:number,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function StartRender(arg1:session.Params):Promise<string>;
